name: tagpr
on:
  push:
    branches:
      - master

jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr-tag: ${{ steps.tagpr.outputs.tag }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - id: tagpr
        name: Run tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger CI Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const refs = '${{ fromJson(steps.tagpr.outputs.pull_request).head.ref }}'
            const { data: pullRequests } = github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: refs
            });

            if (pullRequests.length > 0) {
              const pullRequest = pullRequests[0];
              const git = require('simple-git')();
  
              await git.addConfig('user.name', 'GitHub Actions');
              await git.addConfig('user.email', 'actions@github.com');
  
              await git.checkout(pullRequest.head.ref);
  
              await git.commit('Trigger synchronize event', { '--allow-empty': null });
              
              await git.push(['--force-with-lease']);
            }